#!/usr/bin/env bash
INPUT_FILE=$1
START_LINE=`head -n1 $INPUT_FILE`
ALLOWED_PREFIX="fix: | feat: | Merge "
PATTERN="^($ALLOWED_PREFIX)\w+"
if ! [[ "$START_LINE" =~ $PATTERN ]]; then
  echo "Bad commit message, should follow pattern $ALLOWED_PREFIX"
  exit 1
fi

