name: Makefile CI

on: [push, pull_request]


jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
      
    - name: venv
      run: make setup
      
    - name: test
      run: make test

  semver:
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    needs: test
    steps:
    - name: Semver
      uses: K-Phoen/semver-release-action@master
      with:
        release_branch: main
        release_strategy: none
  
  publish: 
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    needs: test
    name: Build dist and publish
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: venv
      run: make setup

    - name: dist
      run: |
        make dist
        make twine-check
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: dist/*
        
    - name: publish
      run: |
        export TWINE_PASSWORD=${{ secrets.PYPI_TEST_TOKEN }}
        export TWINE_USERNAME=__token__
        make publish
  

# TODO: TAG RELEASE with v
# TODO: Run Test for all branches, release for main
