name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-build-publish:
    name: Build and publish Python distribution
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
      
    - name: venv
      run: make setup
      
    - name: tests
      run: make tests
      
    - name: dist
      run: |
        make dist
        make twine-check
        
    - name: publish
      run: |
        export TWINE_PASSWORD=${{ secrets.PYPI_TEST_TOKEN }}
        export TWINE_USERNAME=__token__
        make publish
    
